Plants/my plants
drewthoennes/timbr pull request #21
Opened 2020-10-06 02:36 UTC by romulus3799

2020-10-06 02:51 UTC, tanyakhandelwal21 commented on src/frontend/components/App/index.jsx
> +        <Nav.Link href="/myplants">My Plants</Nav.Link>
Would you also wanna add logout and home page refs?

2020-10-06 02:54 UTC, tanyakhandelwal21 commented on src/frontend/components/App/index.jsx
> +        <Nav.Link href="/myplants">My Plants</Nav.Link>
And account page!

2020-10-06 03:04 UTC, romulus3799 commented on src/frontend/components/App/index.jsx
> +        <Nav.Link href="/myplants">My Plants</Nav.Link>
This is just a blank navbar for all of us to add our stuff, with mine already added as a reference for you guys.

2020-10-06 22:46 UTC, tanyakhandelwal21 requested changes

2020-10-06 22:46 UTC, tanyakhandelwal21 commented on src/frontend/router/index.jsx
> +      <Route exact path="/myplants" render={() => <MyPlantsPage />} />
All paths are being redirected to / but I think you removed /. Do you wanna redirect to /myplants instead if this is going to be our home page?

2020-10-06 22:46 UTC, tanyakhandelwal21 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +  handleLogout(e) {
Where is this being used?

2020-10-06 22:46 UTC, tanyakhandelwal21 commented on src/frontend/containers/PlantProfilePage/index.jsx
> +class PlantProfilePage extends React.Component {
Since /myplants is the home page, shouldn't we have the account and logout buttons there?

2020-10-07 01:28 UTC, romulus3799 commented on src/frontend/containers/PlantProfilePage/index.jsx
> +class PlantProfilePage extends React.Component {
I haven't touched those buttons, as they're not my stories (I just left them where I found them). Whoever is responsible for them should move them into the top navbar.

2020-10-07 01:28 UTC, romulus3799 commented on src/frontend/router/index.jsx
> +      <Route exact path="/myplants" render={() => <MyPlantsPage />} />
I think we can just leave the homepage blank for now.

2020-10-07 01:38 UTC, tanyakhandelwal21 commented on src/frontend/containers/PlantProfilePage/index.jsx
> +class PlantProfilePage extends React.Component {
The buttons are currently in the [container which is at the route '/'](https://github.com/drewthoennes/timbr/blob/staging/src/frontend/containers/PetsPage/index.jsx), which is supposed to be the home page, as you can see [here](https://github.com/drewthoennes/timbr/blob/staging/src/frontend/router/index.jsx). What your changes are doing is changing that container to be a specific plant's profile page. Would you want to make it a separate container instead and leave my code how it was?

2020-10-07 01:46 UTC, tanyakhandelwal21 commented on src/frontend/router/index.jsx
> +      <Route exact path="/myplants" render={() => <MyPlantsPage />} />
We already have a [home page](https://github.com/drewthoennes/timbr/blob/staging/src/frontend/containers/PetsPage/index.jsx), I'm not sure why that's not being utilised.

2020-10-07 14:47 UTC, drewthoennes requested changes
A few small questions. Also note that linting is failing

2020-10-07 14:47 UTC, drewthoennes commented on src/frontend/containers/MyPlantsPage/styles.scss
> +}
Are these classes used anywhere else in the application? I only ask because without wrapping this in `#my-plants-page { ... }`, these styles will be global and will affect any other `class="plant-card"` and `class="plant-link"` in the application

2020-10-07 14:47 UTC, drewthoennes commented on src/frontend/containers/NewPlantProfilePage/index.jsx
> +      ownedSince: new Date(this.state.ownedSince ?? Date.now())
What do these double question marks do here? It seems like we want OR logic with `||`, but maybe `??` does something that's also sufficient

2020-10-07 14:47 UTC, drewthoennes commented on src/frontend/containers/NewPlantProfilePage/styles.scss
> +}
As mentioned above, we might want to wrap these with `#new-plant-page { ... }` to avoid accidental global styling, though this seems to be the same as your other scss file here

2020-10-07 14:47 UTC, drewthoennes commented on src/frontend/store/actions/pets.js
> +}
Are we using this anywhere? We already have this in `this.props.store.pets`, which it seems you've used above

2020-10-07 23:30 UTC, romulus3799 commented on src/frontend/router/index.jsx
> +      <Route exact path="/myplants" render={() => <MyPlantsPage />} />
That is an older version of the my plants page.

2020-10-07 23:34 UTC, tanyakhandelwal21 commented on src/frontend/router/index.jsx
> +      <Route exact path="/myplants" render={() => <MyPlantsPage />} />
The my plants page does not exist in staging so there can not be an older version. This is the existing home page, that's how the current code treats it.

2020-10-07 23:37 UTC, romulus3799 commented on src/frontend/containers/NewPlantProfilePage/index.jsx
> +      ownedSince: new Date(this.state.ownedSince ?? Date.now())
What `a ?? b` does is: if 'a' is null or undefined, replace it with 'b'.

2020-10-07 23:52 UTC, romulus3799 commented on src/frontend/containers/PlantProfilePage/index.jsx
> +class PlantProfilePage extends React.Component {
Sure, for now I've just put the buttons in the new my plants page, which should be fine until I move them back. I just want to get this branch merged first, because it changes a lot in the frontend.

2020-10-08 13:59 UTC, drewthoennes approved these changes

2020-10-08 14:08 UTC, merged