Plants that require attention
drewthoennes/timbr pull request #58
Opened 2020-11-27 06:34 UTC by niharika01

This merge:
- displays plants that require attention on the homepage
- displays the said action items within the plant card on my plants page

This feature considers the plant's last action date and plant's action frequency to determine if that plant needs attention.

2020-11-27 10:18 UTC, tanyakhandelwal21 requested changes
Functionality works great, I just have some small suggestions!

2020-11-27 10:18 UTC, tanyakhandelwal21 commented on src/frontend/containers/PlantProfilePage/GeneralInformation.jsx
> +        <p>{`Plant's Location: ${location}`}</p>
This seems to show 'Plant's Location: undefined' if I have not set a plant's location. Would you want to show this only if a plant's location has been set?

2020-11-27 10:18 UTC, tanyakhandelwal21 commented on src/frontend/containers/EditPlantProfilePage/index.jsx
> +            <Form.Group controlId="location">
Would you also want to allow adding location when creating a plant?

2020-11-27 10:18 UTC, tanyakhandelwal21 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +        actionItems[id] = `${actionItems[id]}\n Fertilization overdue❗\n`;
nit: The ' ' between \n and Fert.. is inconsistent with the other action items.

2020-11-27 10:18 UTC, tanyakhandelwal21 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +        actionItems[id] = `${actionItems[id]}\nWater overdue❗\n`;
Would you just want to use emojis instead of 'Water overdue!' etc.?

2020-11-28 16:12 UTC, niharika01 commented on src/frontend/containers/EditPlantProfilePage/index.jsx
> +            <Form.Group controlId="location">
Addressed this in the new push.

2020-11-28 16:12 UTC, niharika01 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +        actionItems[id] = `${actionItems[id]}\nWater overdue❗\n`;
Done :)

2020-11-28 18:31 UTC, tanyakhandelwal21 requested changes
Everything else looks good, one small change!

2020-11-28 18:31 UTC, tanyakhandelwal21 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +      if (diffRDays >= 7) {
Shouldn't we use rotateFreq instead of 7 here?

2020-11-28 18:34 UTC, niharika01 commented on src/frontend/containers/MyPlantsPage/index.jsx
> +      if (diffRDays >= 7) {
you're right. I had that there because we had no rotateFreq field in our database. It was added by Drew recently to make the statistics better. I'll have to make this change in other places as well which I will address with my next PR. Good catch! Will update this change here in the next commit.

2020-11-28 19:05 UTC, tanyakhandelwal21 approved these changes

2020-11-28 19:12 UTC, merged